export enum ErrorCode {
    ERR_GIVENS_SIZE_INSUFFICIENT = 'ERR_GIVENS_SIZE_INSUFFICIENT',
    ERR_BOARD_EMPTY = 'ERR_BOARD_EMPTY',
    ERR_BOARD_SIZE_INVALID = 'ERR_BOARD_SIZE_INVALID',
    ERR_BOARD_CHARACTER_INVALID = 'ERR_BOARD_CHARACTER_INVALID',
    ERR_RANGE_UNDEFINED = 'ERR_RANGE_UNDEFINED',
}